---
title: "About this dataset"
---

This data was pulled from the NOAA (National Oceanic and Atmospheric Association) National Climatic Data Center, http://doi.org/10.7289/V5D21VHZ, on August 15, 2017. 

<<<<<<< HEAD
Full data can be downloaded from the website above, however for this analysis we only took observations from New York State weather stations for the years 2000-2010. There are five measures that each of these stations can take, prcp, snow, snwd, tmax and tmin. Prcp is the variable for total precipitation measured for each day in tenths of millimeters. Snow and snwd are the measurements of snowfall and snowdepth respectivley, both recorded in millimeters. Tmax and tmin are the maximum and minimum temperatures recorded for each day, noted in the scale of Celsius (tenths). For each of these measurements there is also a station ID and a date stamp. 
=======
Full data can be downloaded from the website above, however for this analysis we only observed data from stations in New York State from the beginning 2000 to the end of 2010. There are five measures that each of these stations can take: prcp, snow, snwd, tmax and tmin. Prcp is the variable for total precipitation measured for each day in tenths of millimeters. Snow and snwd are the measurements of snowfall and snowdepth respectivley, both recorded in millimeters. Tmax and tmin are the maximum and minimum temperatures recorded for each day, noted in the scale of Celsius (tenths). For each of these measurements there is also a station ID and a date stamp. 
>>>>>>> fec1b485e14e8a3e49f5ab10ad8df29f35f26d70

This information is collected from over 100,000 stations in 180 countries and territories where half of the stations report precipitaiton levels only. Every day the data is checked and maintained to ensure that values continue to be recorded.